### ISSUE TITLE
Update URLs on QuickStart Guide

### ISSUE THREAD

**Issue by Mikejmnez** [OPENDAP/documentation#27]
On the [Introduction](https://opendap.github.io/documentation/QuickStart.html#_introduction), there is a reference to the DAP Protocol, and the URL takes the user to this broken URL: http://www.opendap.org/pdf/ESE-RFC-004v1.1.pdf. I bellieve this is the DAP2 document now findable on Zenodo.

I think that the URL should point to the DAP2 specification on zenodo, and also state the DAP4 spec with proper link.

**Comment by Mikejmnez** [comment]
Another broken URL on the text.
> The [Global Change Master Directory](http://gcmd.gsfc.nasa.gov/) provides...

 on the [GCMD](https://opendap.github.io/documentation/QuickStart.html#_gcmd) subsection.

**Comment by Mikejmnez** [comment]
Another URL that needs to be updated is that of the Hyrax Guide. In the *Note* on section [3.3 Web Interface](https://opendap.github.io/documentation/QuickStart.html#_web_interface), there is a link to the Hyrax Installation Guide, but the one on the Media Wiki. 

Instead, it should point to the new Hyrax Guide.

**Comment by Mikejmnez** [comment]
On [2. What to do With an OPeNDAP URL](https://opendap.github.io/documentation/QuickStart.html#_what_to_do_with_an_opendap_url):

> You could feed it to an OPeNDAP-enabled data analysis package, like [Ferret](http://ferret.wrc.noaa.gov/Ferret), or you could append .ascii

The URL to Ferret is broken. I think we should direct people to pydap's documentation

**Comment by ndp-opendap** [comment]
Ferret is still a thing:

https://ferret.pmel.noaa.gov/Ferret/

But I wonder if the examples work with the current version...

**Comment by ndp-opendap** [comment]
> Another broken URL on the text.
> 
> > The [Global Change Master Directory](http://gcmd.gsfc.nasa.gov/) provides...
> 
> on the [GCMD](https://opendap.github.io/documentation/QuickStart.html#_gcmd) subsection.

GCMD is now located here: https://gcmd.earthdata.nasa.gov

**Comment by Mikejmnez** [comment]
> GCMD is now located here: https://gcmd.earthdata.nasa.gov/

Is the GCMD a tool that people still use? I see that the CMR is listed there, and I know that people use it to search/find data. Which one do you think is most appropriate for the "[Finding OPeNDAP URLs](file:///Users/miguelangeljimenezurias/OPeNDAP/documentation/QuickStart.html#_finding_opendap_urls)?" section?

**Comment by ndp-opendap** [comment]
> > GCMD is now located here: https://gcmd.earthdata.nasa.gov/
> 
> Is the GCMD a tool that people still use? I see that the CMR is listed there, and I know that people use it to search/find data. Which one do you think is most appropriate for the "Finding OPeNDAP URLs?" section?

I don't know. CMR lacks any kind of GUI whack the GCMD Keyword search has such a thing, but I have no idea if GCMD is still a happening thing. For years it was the Godzilla of metadata, but now??

Maybe @jgallagher59701 was something to add here/

**Comment by Mikejmnez** [comment]
closed by #28
